apiVersion: v1
kind: Secret
metadata:
  name: test
  namespace: default
stringData:
  foo: bar


---
apiVersion: experimental.kubesphere.io/v1alpha1
kind: SharingSecret
metadata:
  name: test
spec:
  secretRef:
    namespace: default
    name: test
  target:
#    namespaces:
#      - name: kubesphere-system
#    namespaceSelector:
#      matchExpressions:
#        - key: kubesphere.io/workspace
#          operator: Exists
#      matchLabels:
#        kubesphere.io/workspace: system-workspace:wq
